export const actions = {
  get: 'Получить',
  getting: 'Получение...', 
  gettingSucceed: 'Получение данных прошло успешно',  
  gettingFailed: 'При получение данных произошла ошибка',   
  add: 'Добавить',
  adding: 'Добавление...',
  addingSucceed: 'Добавление прошло успешно',
  addingFailed: 'При добавление произошла ошибка',
  edit: 'Редактировать',
  save: 'Сохранить',
  saving: 'Сохранение...',
  savingSucceed: 'Сохранение прошло успешно',
  savingFailed: 'При сохранении произошла ошибка',
  duplicate: 'Дублировать',
  delete: 'Удалить',
  deleting: 'Удаление...',
  deletingSucceed: 'Удаление прошло успешно',
  deletingFailed: 'При удаление произошла ошибка',
  deleteObject: 'Удалить объект?',
  cancel: 'Отменить',
  clear: 'Отчистить',
  confirm: 'Подтверждаю'
};
